version: '3'

services:
  travel_planner:
    image: travel_planner
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    restart: unless-stopped
    network_mode: "host"
    volumes:
      - .env:/.env
    